# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifu-cli" do
  version "1.1.12"

  on_macos do
    on_intel do
      sha256 "09a3b82e10595a2dfde463b6f8e52209129e9bd148fe35da8448af9f037cc33d"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf8af6cdd2900d82729d17590d6c14bfc32b30ded2a9b40bd6c5b9da155a614f"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "39fd0b85c00310ebdd5efa7ad6fa97b456cf6025988cd7dd990f2b0855f82312"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72c83c29258d5dbccbe1c46b01b957c064cac682a17e5728f7893b10ba62d65e"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_arm64.tar.gz"
    end
  end

  name "bifu-cli"
  desc "BifuFX trading platform CLI — spot, contract, forex, WebSocket, MCP"
  homepage "https://cli.bifu.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifu-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifu-cli"]
    end
  end

  # No zap stanza required

end
