# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifu-cli" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "489e4d2a672fd6a7f989777e0ca715656c99a2d1dd5fcb20109eb9b05f29844f"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "134917b95f04a1388b8d1e3eb41e56d146a4fb1ffbe17edac57f89a3064ef36d"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a28d47568eeff03a9b834c3f7f2a09e1d76315bad99fb03148448a2cdecbf0ff"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93fe9c49b6e532044dd3f861a77c76dae2ce1d9a80c0c8b2b5ecd3e57e801880"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_arm64.tar.gz"
    end
  end

  name "bifu-cli"
  desc "BifuFX trading platform CLI — spot, contract, forex, WebSocket, MCP"
  homepage "https://cli.bifu.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifu-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifu-cli"]
    end
  end

  # No zap stanza required

end
