# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifu-cli" do
  version "1.1.7"

  on_macos do
    on_intel do
      sha256 "1a559138bde75ed097b708c1ee3ee0be4f518b90e7bf1a26e63ba41d3d47a0cd"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d1a02ad8682769c1219f7c9c5fcadb1d22475cf577ff4e8abd1ef9aad5593b8"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29d77c21a956fe3c0e8a43a798a4706cc2554c8fc86946f9c75ac92ecf254a44"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d649b8d24d42963ad0380970f3510ed3ad7b01ac061817ad7dbe4e483e45fab"
      url "https://github.com/decodeex/bifu-cli-releases/releases/download/v#{version}/bifu-cli_linux_arm64.tar.gz"
    end
  end

  name "bifu-cli"
  desc "BifuFX trading platform CLI — spot, contract, forex, WebSocket, MCP"
  homepage "https://cli.bifu.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifu-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifu-cli"]
    end
  end

  # No zap stanza required

end
